// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnOTwYaXtyyqg8MMSdTnnU03SgUsRGJ1w',
    appId: '1:865621798465:web:458ec681e68280831360c0',
    messagingSenderId: '865621798465',
    projectId: 'dody-store-f40d2',
    authDomain: 'dody-store-f40d2.firebaseapp.com',
    storageBucket: 'dody-store-f40d2.firebasestorage.app',
    measurementId: 'G-154K6YK4WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl099pWusMIbRJEzAk1ffCkpVphv-GoQA',
    appId: '1:865621798465:android:5412bd26a4370f1f1360c0',
    messagingSenderId: '865621798465',
    projectId: 'dody-store-f40d2',
    storageBucket: 'dody-store-f40d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM41fhfmdRfeLqqfifGNzNbsCJ8YR9txo',
    appId: '1:865621798465:ios:9dbb3a0a09dd89d31360c0',
    messagingSenderId: '865621798465',
    projectId: 'dody-store-f40d2',
    storageBucket: 'dody-store-f40d2.firebasestorage.app',
    iosBundleId: 'com.Abdelrahman.dodyStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM41fhfmdRfeLqqfifGNzNbsCJ8YR9txo',
    appId: '1:865621798465:ios:9dbb3a0a09dd89d31360c0',
    messagingSenderId: '865621798465',
    projectId: 'dody-store-f40d2',
    storageBucket: 'dody-store-f40d2.firebasestorage.app',
    iosBundleId: 'com.Abdelrahman.dodyStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnOTwYaXtyyqg8MMSdTnnU03SgUsRGJ1w',
    appId: '1:865621798465:web:e21552fcae274d6d1360c0',
    messagingSenderId: '865621798465',
    projectId: 'dody-store-f40d2',
    authDomain: 'dody-store-f40d2.firebaseapp.com',
    storageBucket: 'dody-store-f40d2.firebasestorage.app',
    measurementId: 'G-WTG59BYRJR',
  );

}